### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by dkhamsing** [dkhamsing/how-much#2]
- [ ] no spinner when exactly one twitter account
- [ ] parse paging over 1000 items https://parse.com/questions/fetch-all-data-in-a-table-using-pfquery
- [ ] auto export to web
- [ ] in app export option
- [ ] data import
- [ ] use icloud
- [ ] 1password https://github.com/AgileBits/onepassword-app-extension
- [ ] when switching storage, ask to copy if destination empty??
- [ ] parse - pull to refresh
- [ ] realm 
- [ ] add spinner for edit/add, using parse

# ui
- [ ] get and use gear icon https://thenounproject.com/tenno/
- [ ] app icon white dollar sign
- [ ] make unit smaller than price
- [ ] add alphabet slide on the right

# reference
- https://www.parse.com/apps/how-much--7/collections#class/Item

# done
